from __future__ import annotations

IVER8 = 1
PY_DRIVER_PYMYSQL = 2
PY_DRIVER_SQLALCHEMY = 4

# Python-only iFlag bits (avoid collision with Java bits)
PY_ERROR_CONNECTION_ID = 1 << 21
PY_ERROR_PREPROCESS_BATCHED_ARGS = 1 << 22
PY_ERROR_POSTPROCESS_BATCHED_ARGS = 1 << 23
PY_ERROR_DEFAULT_TZ = 1 << 24
PY_ERROR_SERVER_TZ = 1 << 25
PY_ERROR_ISOLATION = 1 << 26
PY_ERROR_CLIENT_FLAGS = 1 << 27
PY_ERROR_SERVER_FLAGS = 1 << 28
PY_ERROR_SERVER_VERSION = 1 << 29
PY_ERROR_SERVER_HOST = 1 << 30
PY_ERROR_SERVER_INFO = 1 << 31
